using System.Globalization;
using System.Net;
using System.Net.Mail;
using CsvHelper;
using CsvHelper.Configuration;
using Google.GenAI;

// 1. Configuration - Loaded from GitHub Action Environment Variables
var geminiKey = Environment.GetEnvironmentVariable("GEMINI_API_KEY");
var senderEmail = Environment.GetEnvironmentVariable("SENDER_EMAIL");
var appPassword = Environment.GetEnvironmentVariable("SENDER_PASSWORD");
var recipientEmail = Environment.GetEnvironmentVariable("RECIPIENT_EMAIL") ?? senderEmail;
string csvPath = "topics.csv";

csvPath = Path.Combine(AppContext.BaseDirectory, "topics.csv");
if (!File.Exists(csvPath)) 
{
    // Look up for the root folder if running in local debug mode
    csvPath = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "topics.csv"));
}

if (string.IsNullOrWhiteSpace(geminiKey) || string.IsNullOrWhiteSpace(senderEmail) || string.IsNullOrWhiteSpace(appPassword))
{
    Console.WriteLine("❌ Configuration Error: Missing GEMINI_API_KEY, SENDER_EMAIL, or SENDER_PASSWORD.");
    return;
}

string baseDir = AppContext.BaseDirectory;
// 2. Read Topics from CSV
var csvConfig = new CsvConfiguration(CultureInfo.InvariantCulture) { HasHeaderRecord = true };
List<TopicRow> records = new();

if (!File.Exists(csvPath))
{
    csvPath = Path.GetFullPath(Path.Combine(baseDir, "..", "..", "..", "topics.csv"));
}

if (!File.Exists(csvPath))
{
    Console.WriteLine($"❌ File not found at: {csvPath}");
    return;
}

Console.WriteLine($"✅ Using CSV found at: {csvPath}");

using (var reader = new StreamReader(csvPath))
using (var csv = new CsvReader(reader, csvConfig))
{
    records = csv.GetRecords<TopicRow>().ToList();
}

var nextTopic = records.FirstOrDefault(r => !r.IsPosted);
if (nextTopic == null)
{
    Console.WriteLine("✅ All topics in the CSV have already been drafted.");
    return;
}

// 3. Generate Content using the Official Google.GenAI Client
try
{
    var client = new Client(apiKey: geminiKey);

    string prompt = $"""
        Role: Expert .NET Tech Lead.
        Topic: {nextTopic.Title}
        Task: Write a high-authority LinkedIn post for senior developers.
        Include:
        - A punchy hook addressing an architectural challenge.
        - 3 key technical insights.
        - A clean C# code snippet (using .NET 8/9 syntax).
        - A closing question for the community.
        Tone: Professional and concise.
        Signature: 🚀 #asp.net core #dotnet #csharp #azure
        """;

    var response = await client.Models.GenerateContentAsync("gemini-2.5-flash", prompt);

    // FIX: Access the text through Candidates -> Content -> Parts
    var postText = response.Candidates?[0].Content?.Parts?[0].Text
                   ?? "Error: No text was generated by the model.";

    if (string.IsNullOrEmpty(postText))
    {
        Console.WriteLine("⚠️ Model returned an empty response.");
        return;
    }

    // 4. Send the Email via Gmail SMTP
    using var smtpClient = new SmtpClient("smtp.gmail.com", 587)
    {
        Credentials = new NetworkCredential(senderEmail, appPassword),
        EnableSsl = true
    };

    var mail = new MailMessage
    {
        From = new MailAddress(senderEmail),
        Subject = $"✨ LinkedIn Draft: {nextTopic.Title}",
        Body = $"Review your generated post below:\n\n---\n\n{postText}\n\n---\n\nSent via BinaryDrop Automation.",
        IsBodyHtml = false
    };
    mail.To.Add(recipientEmail!);

    await smtpClient.SendMailAsync(mail);
    Console.WriteLine($"📧 Draft sent successfully for: {nextTopic.Title}");

    // 5. Update CSV State and Save
    nextTopic.IsPosted = true;
    using (var writer = new StreamWriter(csvPath))
    using (var csv = new CsvWriter(writer, csvConfig))
    {
        csv.WriteRecords(records);
    }
    Console.WriteLine("💾 topics.csv updated.");
}
catch (Exception ex)
{
    Console.WriteLine($"❌ Error: {ex.Message}");
}

public class TopicRow
{
    public int Id { get; set; }
    public string Title { get; set; } = string.Empty;
    public bool IsPosted { get; set; }
}
